name: CI with OpenID Connect

on:
    push:
        branches: [ master ]
        paths:
          - frontend/**

permissions:
      id-token: write
      contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        node-version: [14.x]
    name: Node ${{ matrix.java }}
    env:
      OS: ${{ matrix.os }}
      NODE_VERSION: ${{ matrix.node-version }}
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install
      working-directory: ./frontend
      run: npm ci
    - name: Build
      working-directory: ./frontend
      run: npm run build --if-present
    - name: Test
      working-directory: ./frontend
      run: npm test
    - uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        inlineScript: |
            az storage blob upload-batch --account-name  facerecogwebsite --auth-mode key -d '$web' -s ./frontend/public/ --overwrite
  # Azure logout
    - name: logout
      run: |
            az logout
      if: always()
